# Generated by Django 5.0.6 on 2024-07-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
