# Generated by Django 5.0.6 on 2024-07-23 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_remove_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
